# 1. Compiler and Flags
CC = gcc
#uncomment whats below for profiling with soft float. need to install the toolchain and this will cross compile for the arm vm with soft floating point instructions
# TOOLCHAIN = $(HOME)/toolchains/armv5-eabi--glibc--stable-2025.08-1
# CC = $(TOOLCHAIN)/bin/arm-buildroot-linux-gnueabi-gcc
#CFLAGS = -g -Iinclude -Wall -O2 -MMD -MP -mtune=cortex-a7 -mfloat-abi=soft
CFLAGS = -g -Iinclude -Wall -O2 -MMD -MP -mtune=cortex-a7 -mfpu=neon 
#CFLAGS = -g -Iinclude -Wall  -MMD -MP 
#linker flags uncomment for cross compile with soft floating point (wont run locally if uncommented)
# LDFLAGS = -static -mfloat-abi=soft
# Add the math library
LDLIBS = -lm
# 2. Directories and Files
SRC_DIR = src
OBJ_DIR = obj
ASM_DIR = asm
# Automatically find all .c files in the src directory
SRCS = $(wildcard $(SRC_DIR)/*.c)
# Convert the list of .c files into .o (object) files inside the obj directory
OBJS = $(SRCS:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)
# Assembly output files
ASMS = $(SRCS:$(SRC_DIR)/%.c=$(ASM_DIR)/%.s)
# Per-object header dependency files generated by -MMD
DEPS = $(OBJS:.o=.d)
# 3. Target Executable
TARGET = filters
# Default rule
all: $(TARGET) $(ASMS)
# Link object files into the final executable
$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $(TARGET) $(LDLIBS)
# Pattern rule: Compile each .c file into a .o file
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
# Pattern rule: Generate assembly for each .c file
$(ASM_DIR)/%.s: $(SRC_DIR)/%.c | $(ASM_DIR)
	$(CC) $(filter-out -MMD -MP,$(CFLAGS)) -fverbose-asm -S $< -o $@
# Create the object directory if it does not exist
$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)
$(ASM_DIR):
	mkdir -p $(ASM_DIR)
# Clean up build files
clean:
	rm -rf $(OBJ_DIR) $(ASM_DIR) $(TARGET)
# Pull in generated header dependencies so editing a header rebuilds
# every .c file that includes it
-include $(DEPS)
.PHONY: all clean